<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="language" nsURI="http://www.abchip.org/mimo/language" nsPrefix="mimo-lang">
  <eClassifiers xsi:type="ecore:EClass" name="Language" eSuperTypes="../../org.abchip.mimo.core/model/mimo.ecore#//entity/EntityNameable ../../org.abchip.mimo.core/model/mimo.ecore#//entity/Textable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iso_639_1" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scope" lowerBound="1" eType="#//LanguageScope"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//LanguageType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LanguageExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expressionRow" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LanguageManager" abstract="true" interface="true">
    <eOperations name="classifyLanguage" lowerBound="1">
      <eGenericType eClassifier="ecore:EClass ../../org.abchip.mimo.mining/model/mining.ecore#//classification/Classification">
        <eTypeArguments eClassifier="#//Language"/>
      </eGenericType>
      <eParameters name="contextProvider" lowerBound="1" eType="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//context/ContextProvider"/>
      <eParameters name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="translate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="contextProvider" lowerBound="1" eType="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//context/ContextProvider"/>
      <eParameters name="languageSource" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="languageTarget" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LanguageParser" abstract="true" interface="true">
    <eOperations name="parse" lowerBound="1" eType="#//LanguageExpression">
      <eParameters name="contextProvider" lowerBound="1" eType="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//context/ContextProvider"/>
      <eParameters name="language" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LanguageParserRegistry" abstract="true"
      interface="true">
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//context/Registry">
      <eTypeArguments eClassifier="#//LanguageParser"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LanguageScope">
    <eLiterals name="I" value="10" literal="Individual"/>
    <eLiterals name="M" value="20" literal="Macrolanguage"/>
    <eLiterals name="C" value="30" literal="Collections"/>
    <eLiterals name="R" value="40" literal="Reserved"/>
    <eLiterals name="S" value="50" literal="Specials"/>
    <eLiterals name="D" value="60" literal="Dialects"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LanguageType">
    <eLiterals name="L" value="10" literal="Living"/>
    <eLiterals name="E" value="20" literal="Extinct"/>
    <eLiterals name="A" value="30" literal="Ancient"/>
    <eLiterals name="H" value="40" literal="Historical"/>
    <eLiterals name="C" value="50" literal="Constructed"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LanguageLinearizer" abstract="true"
      interface="true">
    <eOperations name="linearize" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="contextProvider" lowerBound="1" eType="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//context/ContextProvider"/>
      <eParameters name="language" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="expression" lowerBound="1" eType="#//LanguageExpression"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LanguageLinearizerRegistry" abstract="true"
      interface="true">
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.abchip.mimo.core/model/mimo.ecore#//context/Registry">
      <eTypeArguments eClassifier="#//LanguageLinearizer"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eSubpackages name="grammar" nsURI="http://www.abchip.org/mimo/language/grammar"
      nsPrefix="mimo-gram">
    <eClassifiers xsi:type="ecore:EClass" name="Adjective" eSuperTypes="#//grammar/Word"/>
    <eClassifiers xsi:type="ecore:EClass" name="Dialog" eSuperTypes="../../org.abchip.mimo.core/model/mimo.ecore#//entity/Entity"/>
    <eClassifiers xsi:type="ecore:EEnum" name="Gender">
      <eLiterals name="M" value="10" literal="Masculine"/>
      <eLiterals name="F" value="20" literal="Feminine"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Grammar" eSuperTypes="../../org.abchip.mimo.core/model/mimo.ecore#//entity/EntityNameable ../../org.abchip.mimo.core/model/mimo.ecore#//entity/Textable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Noun" eSuperTypes="#//grammar/Word"/>
    <eClassifiers xsi:type="ecore:EEnum" name="Number">
      <eLiterals name="S" value="10" literal="Singular"/>
      <eLiterals name="P" value="20" literal="Plural"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Predicate" eSuperTypes="../../org.abchip.mimo.core/model/mimo.ecore#//entity/Entity"/>
    <eClassifiers xsi:type="ecore:EClass" name="Pronoun" eSuperTypes="#//grammar/Word"/>
    <eClassifiers xsi:type="ecore:EClass" name="Sentence" eSuperTypes="../../org.abchip.mimo.core/model/mimo.ecore#//entity/Entity"/>
    <eClassifiers xsi:type="ecore:EClass" name="Verb" eSuperTypes="#//grammar/Word"/>
    <eClassifiers xsi:type="ecore:EClass" name="Word" eSuperTypes="../../org.abchip.mimo.core/model/mimo.ecore#//entity/EntityNameable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
